# Generated by Django 2.0.5 on 2018-05-26 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubName', models.CharField(max_length=50)),
                ('SubID', models.CharField(max_length=50)),
                ('ChapterName', models.CharField(max_length=50)),
                ('Question', models.TextField(max_length=1000)),
                ('Option1', models.CharField(max_length=50)),
                ('Option2', models.CharField(max_length=50)),
                ('Option3', models.CharField(max_length=50)),
                ('Option4', models.CharField(max_length=50)),
                ('CorrectAns', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ChapterQuestion',
            },
        ),
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TableName', models.CharField(max_length=15)),
                ('marks', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'ExamHistory',
            },
        ),
        migrations.CreateModel(
            name='ExQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.TextField(max_length=1000)),
                ('Option1', models.CharField(max_length=50)),
                ('Option2', models.CharField(max_length=50)),
                ('Option3', models.CharField(max_length=50)),
                ('Option4', models.CharField(max_length=50)),
                ('CorrectAns', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'ExQuestion',
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionName', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'QuestionSet',
            },
        ),
        migrations.AddField(
            model_name='exquestion',
            name='QuestionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionSet'),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='Question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionSet'),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
