# Generated by Django 2.0.5 on 2018-05-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterquestion',
            name='MVD',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exquestion',
            name='MVD',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
