# Generated by Django 2.0.5 on 2018-05-27 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180527_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examhistory',
            old_name='Question_id',
            new_name='QuestionId',
        ),
        migrations.AddField(
            model_name='chapterquestion',
            name='QuestionId',
            field=models.ForeignKey(default=1995, on_delete=django.db.models.deletion.CASCADE, to='questions.QuestionSet'),
            preserve_default=False,
        ),
    ]
