# Generated by Django 2.0.5 on 2018-05-27 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20180527_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examhistory',
            old_name='User_id',
            new_name='UserId',
        ),
    ]
