# Generated by Django 2.0.5 on 2018-06-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20180527_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examhistory',
            name='marks',
            field=models.FloatField(null=True),
        ),
    ]
