# Generated by Django 2.0.5 on 2018-06-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20180601_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notice', models.CharField(max_length=2000)),
                ('Due_date', models.DateTimeField(null=True)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Noticeboard',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdToken', models.CharField(max_length=100)),
                ('userID', models.CharField(max_length=100)),
                ('Name', models.TextField(max_length=1000)),
                ('Email', models.CharField(max_length=50)),
                ('Avatar', models.ImageField(null=True, upload_to='')),
                ('Balance', models.IntegerField(default=0)),
                ('Gender', models.CharField(max_length=5, null=True)),
                ('Date_of_birth', models.DateField(null=True)),
            ],
            options={
                'db_table': 'Profile',
            },
        ),
        migrations.RemoveField(
            model_name='examhistory',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='examhistory',
            name='position',
        ),
        migrations.AddField(
            model_name='chapterquestion',
            name='Equation',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='Marks',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='examhistory',
            name='Position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exquestion',
            name='Equation',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
