# Generated by Django 2.0.5 on 2018-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20180609_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='IdToken',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='userID',
        ),
        migrations.AddField(
            model_name='profile',
            name='ProviderID',
            field=models.CharField(default='Google', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='UserID',
            field=models.CharField(default='asw3dfsa', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='Notice',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='ChapterName',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='CorrectAns',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='Option1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='Option2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='Option3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='Option4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='SubID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chapterquestion',
            name='SubName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='examhistory',
            name='TableName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exquestion',
            name='CorrectAns',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='exquestion',
            name='Option1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exquestion',
            name='Option2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exquestion',
            name='Option3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exquestion',
            name='Option4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='QuestionName',
            field=models.CharField(max_length=1000),
        ),
    ]
