# Generated by Django 2.0.5 on 2018-06-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_auto_20180613_1031'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='ProfileMod',
        ),
    ]
