# Generated by Django 2.0.5 on 2018-06-13 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20180613_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examhistory',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.ProfileMod'),
        ),
    ]
